### ISSUE TITLE
No Data from P1

### ISSUE THREAD

**Issue by hemant5400z** [MadPatrick/domoticz_toon#3]
Hi,

I just installed this plugin for my rooted Toon V1 as per instructions I tried V1 and also userdefined.
However I don't get data for the P1 devices. 

Hemant

**Comment by MadPatrick** [comment]
Do you have your P1 connected to your Toon
What is the output of the json?

**Comment by hemant5400z** [comment]
Hi Yes I have I can see the data on Toon:
```
{
	"dev_settings_device": {
		"uuid": "5e572aad-82d5-4d7b-9552-c81b6bb46b7e",
		"name": "settings_device",
		"internalAddress": "settings_device",
		"type": "settings_device"
	},
	"dev_3": {
		"uuid": "49c9f652-ee80-4f8b-a300-a73e5649941e",
		"name": "HAE_METER_v2",
		"internalAddress": "3",
		"type": "HAE_METER_v2",
		"supportsCrc": "1",
		"ccList": "22 3c 3d 3e 56 60 70 72 7a 86 8b 73",
		"supportedCC": "22 3c 3d 3e 56 60 70 72 7a 86 8b 73",
		"nodeFlags": [],
		"IsConnected": "1",
		"HealthValue": "8",
		"DeviceName": "HAE_METER_v2",
		"CurrentSensorStatus": "UNKNOWN"
	},
	"dev_3.1": {
		"uuid": "ae32a545-7eea-467f-bb43-dc3576a72556",
		"name": "HAE_METER_v2_1",
		"internalAddress": "3.1",
		"type": "HAE_METER_v2_1",
		"supportsCrc": "0",
		"ccList": "3c 3d 3e 72 86",
		"supportedCC": "3c 3d 3e 72 86",
		"nodeFlags": [],
		"CurrentSensorStatus": "OPERATIONAL",
		"CurrentGasFlow": "0.00",
		"CurrentGasQuantity": "921329.00",
		"DeviceName": "HAE_METER_v2_1"
	},
	"dev_3.2": {
		"uuid": "80bad6e0-681a-4193-aebc-0139ed974309",
		"name": "HAE_METER_v2_2",
		"internalAddress": "3.2",
		"type": "HAE_METER_v2_2",
		"supportsCrc": "0",
		"ccList": "3c 3d 3e 72 86",
		"supportedCC": "3c 3d 3e 72 86",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "HAE_METER_v2_2",
		"CurrentElectricityFlow": "NaN",
		"CurrentElectricityQuantity": "NaN"
	},
	"dev_3.3": {
		"uuid": "65d75acc-6ed8-4e8a-8521-505b94d331bd",
		"name": "HAE_METER_v2_3",
		"internalAddress": "3.3",
		"type": "HAE_METER_v2_3",
		"supportsCrc": "0",
		"ccList": "3c 3d 3e 72 86",
		"supportedCC": "3c 3d 3e 72 86",
		"nodeFlags": [],
		"CurrentSensorStatus": "OPERATIONAL",
		"DeviceName": "HAE_METER_v2_3",
		"CurrentElectricityFlow": "199.00",
		"CurrentElectricityQuantity": "3846824.00"
	},
	"dev_3.4": {
		"uuid": "0f7ca805-1a6e-4025-8c00-83f1ec0dd4bc",
		"name": "HAE_METER_v2_4",
		"internalAddress": "3.4",
		"type": "HAE_METER_v2_4",
		"supportsCrc": "0",
		"ccList": "3c 3d 3e 72 86",
		"supportedCC": "3c 3d 3e 72 86",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "HAE_METER_v2_4",
		"CurrentElectricityFlow": "0.00",
		"CurrentElectricityQuantity": "2260288.00"
	},
	"dev_3.5": {
		"uuid": "1c7ac58f-bfb1-4101-a88b-53bab7643ee0",
		"name": "HAE_METER_v2_5",
		"internalAddress": "3.5",
		"type": "HAE_METER_v2_5",
		"supportsCrc": "0",
		"ccList": "3c 3d 3e 72 86",
		"supportedCC": "3c 3d 3e 72 86",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "HAE_METER_v2_5",
		"CurrentElectricityFlow": "0.00",
		"CurrentElectricityQuantity": "3413210.00"
	},
	"dev_3.6": {
		"uuid": "8b59596d-f5ec-47e0-9e3d-92384ed0159d",
		"name": "HAE_METER_v2_6",
		"internalAddress": "3.6",
		"type": "HAE_METER_v2_6",
		"supportsCrc": "0",
		"ccList": "3c 3d 3e 72 86",
		"supportedCC": "3c 3d 3e 72 86",
		"nodeFlags": [],
		"CurrentSensorStatus": "UNKNOWN",
		"DeviceName": "HAE_METER_v2_6",
		"CurrentElectricityFlow": "0.00",
		"CurrentElectricityQuantity": "939227.00"
	}
}
```

**Comment by hemant5400z** [comment]
Also my Gas keeps dissapearing and in domoticz error log I see:

2023-01-10 12:45:00.820 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 12:50:00.681 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 12:55:00.556 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 13:00:00.468 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 13:01:00.754 Error: Gas - invalid value: ''
2023-01-10 13:05:01.509 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 13:10:00.859 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 13:15:00.709 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 13:20:00.937 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)
2023-01-10 13:25:01.403 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 293, sValue: '', sUsage: '0', dType: 251, sType: 2)


Hemant

**Comment by MadPatrick** [comment]
What value do you fill in. 
I see you numbers are 3.x

**Comment by hemant5400z** [comment]
Hi,

I used the settings for V1 as described in the readme: 2.1;2.3;2.5;2.4;2.6

Hemant

**Comment by MadPatrick** [comment]
That is the problem with the Toon. 
Most people have 2.x number. 
Some 3.x and even people with 4.x

For that reason is the user defined field. 
I'll update the instructions next week. 

So you need to use the 3.x mumbers as in your json

**Comment by hemant5400z** [comment]
Hi,

I used 3.1;3.4;3.6;3.5;3.7

I can now see Gas but others are still empty.
Hemant

**Comment by MadPatrick** [comment]
Try to restart Domoticz. 
This helps sometime. 

Dontoubsee anything in the log?

**Comment by hemant5400z** [comment]
Log seems clear now, think it is something with the value sequence.

I now have GAS, Toons electricity and P1, Toon Opgewekte Electriciteit is still 0.

These are the current values: 
User defined
3.1;3.3;3.4;3.5;3.6

**Comment by MadPatrick** [comment]
Good. 
Solar power is probably very low ar the moment so could be 0
Check the generated power from your solar device minus used power

**Comment by JanJaapKo** [comment]
I reformatted the comment with the JSON in it, you can check if the right numbers are used.

**Comment by hemant5400z** [comment]
currently generating solar according to my toon (using enphase) 347 watts but Toon in Domoticz shows 0 watts, something not alligned with my config.

hemant

**Comment by MadPatrick** [comment]
Generated is not the same as returned power. 
But check the json and log. 
You should find the value over there.

**Comment by hemant5400z** [comment]
Ah indeed, return is 0 watts, today probably bad example :)

**Comment by hemant5400z** [comment]
Do I need to use this sequence?
3.1;3.2;3.3;3.4;3.5;3.6;

do get the correct mapping? or do I need to skip 3.2 because it shows NaN

**Comment by JanJaapKo** [comment]
@MadPatrick  I think the order should indeed be described, we kind of lost that when removing the individual settings fields for the ZWave adresses.....

**Comment by MadPatrick** [comment]
No problem , but i'm now on vacation. 
I will try if i can find something quickly on my mobile.

**Comment by hemant5400z** [comment]
My best guess:

Gas 3.1
Toon Electriciteit: 3.3
Toon Opgewekte electriciteit: 3.4
Toon P1: 3.5 & 3.6   

Hemant

**Comment by JanJaapKo** [comment]
from the code, it must be provided in this order:
1: ia_gas=gas
2: ia_ednt = Elec Normal
3: ia_edlt = Elec Low
4: ia_ernt = Elec Normal return 
5: ia_erlt = Elec Low return

**Comment by hemant5400z** [comment]
Hi,

checking the status for domoticz devices now that i'm returning but it it still not ok:

`{"dev_settings_device": {"uuid": "5e572aad-82d5-4d7b-9552-c81b6bb46b7e", "name": "settings_device", "internalAddress": "settings_device", "type": "settings_device"}, "dev_3": {"uuid": "49c9f652-ee80-4f8b-a300-a73e5649941e", "name": "HAE_METER_v2", "internalAddress": "3", "type": "HAE_METER_v2", "supportsCrc": "1", "ccList": "22 3c 3d 3e 56 60 70 72 7a 86 8b 73", "supportedCC": "22 3c 3d 3e 56 60 70 72 7a 86 8b 73", "nodeFlags": [], "IsConnected": "1", "HealthValue": "2", "DeviceName": "HAE_METER_v2", "CurrentSensorStatus": "UNKNOWN"}, "dev_3.1": {"uuid": "ae32a545-7eea-467f-bb43-dc3576a72556", "name": "HAE_METER_v2_1", "internalAddress": "3.1", "type": "HAE_METER_v2_1", "supportsCrc": "0", "ccList": "3c 3d 3e 72 86", "supportedCC": "3c 3d 3e 72 86", "nodeFlags": [], "CurrentSensorStatus": "OPERATIONAL", "CurrentGasFlow": "NaN", "CurrentGasQuantity": "926901.00", "DeviceName": "HAE_METER_v2_1"}, "dev_3.2": {"uuid": "80bad6e0-681a-4193-aebc-0139ed974309", "name": "HAE_METER_v2_2", "internalAddress": "3.2", "type": "HAE_METER_v2_2", "supportsCrc": "0", "ccList": "3c 3d 3e 72 86", "supportedCC": "3c 3d 3e 72 86", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v2_2", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"}, "dev_3.3": {"uuid": "65d75acc-6ed8-4e8a-8521-505b94d331bd", "name": "HAE_METER_v2_3", "internalAddress": "3.3", "type": "HAE_METER_v2_3", "supportsCrc": "0", "ccList": "3c 3d 3e 72 86", "supportedCC": "3c 3d 3e 72 86", "nodeFlags": [], "CurrentSensorStatus": "OPERATIONAL", "DeviceName": "HAE_METER_v2_3", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "3857356.00"}, "dev_3.4": {"uuid": "0f7ca805-1a6e-4025-8c00-83f1ec0dd4bc", "name": "HAE_METER_v2_4", "internalAddress": "3.4", "type": "HAE_METER_v2_4", "supportsCrc": "0", "ccList": "3c 3d 3e 72 86", "supportedCC": "3c 3d 3e 72 86", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v2_4", "CurrentElectricityFlow": "733.00", "CurrentElectricityQuantity": "2260537.00"}, "dev_3.5": {"uuid": "1c7ac58f-bfb1-4101-a88b-53bab7643ee0", "name": "HAE_METER_v2_5", "internalAddress": "3.5", "type": "HAE_METER_v2_5", "supportsCrc": "0", "ccList": "3c 3d 3e 72 86", "supportedCC": "3c 3d 3e 72 86", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v2_5", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "3416235.00"}, "dev_3.6": {"uuid": "8b59596d-f5ec-47e0-9e3d-92384ed0159d", "name": "HAE_METER_v2_6", "internalAddress": "3.6", "type": "HAE_METER_v2_6", "supportsCrc": "0", "ccList": "3c 3d 3e 72 86", "supportedCC": "3c 3d 3e 72 86", "nodeFlags": [], "CurrentSensorStatus": "UNKNOWN", "DeviceName": "HAE_METER_v2_6", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "939227.00"}}
`
In the error log of domoticz i see this:
```
2023-01-11 11:23:52.332 Error: Toon: Exception traceback:
2023-01-11 11:23:52.333 Error: Toon: ----> Line 569 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:23:52.333 Error: Toon: ----> Line 472 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:23:52.333 Error: Toon: ----> Line 413 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:24:12.407 Error: Toon: 'onMessage' failed 'ValueError':'cannot convert float NaN to integer'.
2023-01-11 11:24:12.407 Error: Toon: Exception traceback:
2023-01-11 11:24:12.408 Error: Toon: ----> Line 569 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:24:12.408 Error: Toon: ----> Line 472 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:24:12.408 Error: Toon: ----> Line 413 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:24:32.593 Error: Toon: 'onMessage' failed 'ValueError':'cannot convert float NaN to integer'.
2023-01-11 11:24:32.593 Error: Toon: Exception traceback:
2023-01-11 11:24:32.593 Error: Toon: ----> Line 569 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:24:32.593 Error: Toon: ----> Line 472 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:24:32.593 Error: Toon: ----> Line 413 in '/config/plugins/domoticz_toon-main/plugin.py'
2023-01-11 11:24:52.321 Error: Toon: 'onMessage' failed 'ValueError':'cannot convert float NaN to integer'.
2023-01-11 11:24:52.321 Error: Toon: Exception traceback:

```

Cheers,
hemant

**Comment by hemant5400z** [comment]
After going through the jason file mine should be like this:

1: ia_gas=gas    3.1
2: ia_ednt = Elec Normal 3.3
3: ia_edlt = Elec Low 3.5
4: ia_ernt = Elec Normal return 3.4
5: ia_erlt = Elec Low return 3.6

which I configured  3.1;3.3;3.5;3.4;3.6 as user defined

But I get One or more Zwave internal address not configured correctly

![image](https://user-images.githubusercontent.com/16900394/211866576-9335f544-d331-4ead-9a94-cea3ba4f6d7e.png)

![image](https://user-images.githubusercontent.com/16900394/211866784-9a6fdc21-adfa-4b7a-84d9-d80134043424.png)

**Comment by JanJaapKo** [comment]
That error occurs when the received data cannot be converted to a number correctly. This is handled not very elegantly. I'm assuming this will be the case for the 2 instances of NaN (Not a Number). Can you confirm that those devices were not updated? I'll try to catch those errors in a bit better way.

**Comment by JanJaapKo** [comment]
I just pushed version 1.4.3 this should fix it. Please try and let me know

**Comment by hemant5400z** [comment]
Looks like this is working

![image](https://user-images.githubusercontent.com/16900394/212060516-4e62b09a-4c10-4af3-9566-841719ea35af.png)


Toon -Opgewekt (is the returning data right i asssume)

Hemant

**Comment by MadPatrick** [comment]
> @MadPatrick I think the order should indeed be described, we kind of lost that when removing the individual settings fields for the ZWave adresses.....

It is not that easy as it looks
I can 't find any information from the Toon which parmeter is connect with a dev_x.x

For me this is the configuration:

```
2.1     self.ia_gas=paramList[0]             jsonGasPower.dev_21.CurrentGasQuantity
2.4     self.ia_ednt=paramList[1]           jsonGasPower.dev_24.CurrentElectricityQuantity
2.6     self.ia_edlt=paramList[2]            jsonGasPower.dev_26.CurrentElectricityQuantity
2.5     self.ia_ernt=paramList[3]            jsonGasPower.dev_25.CurrentElectricityQuantity
2.7     self.ia_erlt=paramList[4]             jsonGasPower.dev_27.CurrentElectricityQuantity
```

When you execute the JSON  http://TOON_IP/hdrv_zwave?action=getDevices it generates this info:

```
// 20230115110453
// http://192.168.1.200/hdrv_zwave?action=getDevices

{
  "dev_2": {
    "uuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "name": "HAE_METER_v3",
    "type": "HAE_METER_v3",
    "nodeIdInfo": {
      "nodeId": 2,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "86",
      "72",
      "32",
      "56",
      "5a",
      "59",
      "85",
      "73",
      "7a",
      "60",
      "8e",
      "22",
      "70",
      "8b",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "manufacturerInfo": {
      "manufacturerId": "0130",
      "productId": "0000",
      "productTypeId": "0002"
    },
    "profileInfo": {
      "IsConnected": 1,
      "HealthValue": 10,
      "DeviceName": "HAE_METER_v3",
      "CurrentSensorStatus": "UNKNOWN"
    }
  },
  "dev_2.1": {
    "uuid": "d9c5dbad-517f-4107-8c07-3be0596e42b3",
    "name": "HAE_METER_v3_1",
    "type": "HAE_METER_v3_1",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 1,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "CurrentGasFlow": 74.0,
      "CurrentGasQuantity": 9410168.0,
      "DeviceName": "HAE_METER_v3_1",
      "CurrentSensorStatus": "OPERATIONAL"
    }
  },
  "dev_2.2": {
    "uuid": "7eb33e27-9d1d-419c-ac0b-3fadfb7baa67",
    "name": "HAE_METER_v3_2",
    "type": "HAE_METER_v3_2",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 2,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "DeviceName": "HAE_METER_v3_2",
      "CurrentElectricityFlow": null,
      "CurrentElectricityQuantity": null,
      "CurrentSensorStatus": "DISABLED"
    }
  },
  "dev_2.3": {
    "uuid": "f42d1623-6d57-49e7-b43b-5bfb5104f09f",
    "name": "HAE_METER_v3_3",
    "type": "HAE_METER_v3_3",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 3,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "DeviceName": "HAE_METER_v3_3",
      "CurrentElectricityFlow": 433.0,
      "CurrentElectricityQuantity": 199682.0,
      "CurrentSensorStatus": "OPERATIONAL"
    }
  },
  "dev_2.4": {
    "uuid": "e1818976-b7f0-4dbe-a9c7-171cea5fe208",
    "name": "HAE_METER_v3_4",
    "type": "HAE_METER_v3_4",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 4,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "DeviceName": "HAE_METER_v3_4",
      "CurrentElectricityFlow": 0.0,
      "CurrentElectricityQuantity": 13056778.0,
      "CurrentSensorStatus": "OPERATIONAL"
    }
  },
  "dev_2.5": {
    "uuid": "ab5142fb-9f72-4a21-a412-ebca6e225828",
    "name": "HAE_METER_v3_5",
    "type": "HAE_METER_v3_5",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 5,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "DeviceName": "HAE_METER_v3_5",
      "CurrentElectricityFlow": 0.0,
      "CurrentElectricityQuantity": 7956260.0,
      "CurrentSensorStatus": "UNKNOWN"
    }
  },
  "dev_2.6": {
    "uuid": "3002274d-633d-4222-b7a0-927415fad553",
    "name": "HAE_METER_v3_6",
    "type": "HAE_METER_v3_6",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 6,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "DeviceName": "HAE_METER_v3_6",
      "CurrentElectricityFlow": 21.0,
      "CurrentElectricityQuantity": 13102233.0,
      "CurrentSensorStatus": "UNKNOWN"
    }
  },
  "dev_2.7": {
    "uuid": "471a324b-cfdd-42a3-b487-6dcab6d292d5",
    "name": "HAE_METER_v3_7",
    "type": "HAE_METER_v3_7",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 7,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "DeviceName": "HAE_METER_v3_7",
      "CurrentElectricityFlow": 0.0,
      "CurrentElectricityQuantity": 3130794.0,
      "CurrentSensorStatus": "UNKNOWN"
    }
  },
  "dev_2.8": {
    "uuid": "3011b15c-c8e6-45dd-acbc-029edbd3dfb5",
    "name": "HAE_METER_v3_8",
    "type": "HAE_METER_v3_8",
    "parentUuid": "670f6fb2-c7af-4ddb-a3fd-b88c88df7cc5",
    "nodeIdInfo": {
      "nodeId": 2,
      "endPoint": 8,
      "useCrc": true
    },
    "supportedCC": [
      "5e",
      "59",
      "85",
      "8e",
      "3c",
      "3d",
      "3e"
    ],
    "nodeFlags": [
      
    ],
    "profileInfo": {
      "DeviceName": "HAE_METER_v3_8",
      "CurrentHeatQuantity": null,
      "CurrentSensorStatus": "UNKNOWN",
      "CurrentHeatFlow": null
    }
  }
}
```

No specific information to use unfortunately

**Comment by JanJaapKo** [comment]
> Toon -Opgewekt (is the returning data right i asssume)

As this is measured at the meter, it is indeed the return, which is not the same as 'opgewekt', _return = opgewekt - verbruikt_
The real generated energy you can only measure at your solar panel's inverter. Depending which brand, several plugins are available (I'm maintaining one for Goodwe for example)


@MadPatrick  that info is not very descriptive indeed. So the readme should then describe that the user can use the 2 pre defined profiles or otherwise needs to figure it out for themselves. So we should describe the steps: runs this endpoint, and put in the numbers in the order:
1: gas 
2: Elec Normal 
3: Elec Low 
4: Elec Normal return
5: Elec Low return
Where normal = normal/day rate and low = low/night rate

**Comment by MadPatrick** [comment]
I will update the readme with more instructions

**Comment by hemant5400z** [comment]
Hi All,

I have been monitoring (finally some sun Today, enough to return). However I don't see anything in Domoticz "Toon Opgewekte Electriciteit".




![image](https://user-images.githubusercontent.com/16900394/212928467-ef06ca6b-d438-41c2-bd9d-e1ccff6dbba9.png)



Is there an explanation for this behavior?

Thanks,
Hemant

**Comment by MadPatrick** [comment]
Can you check in the JSON the values of dev_3.5 and dev_3.7 on CurrentElectricityFlow
If you have power returned there should be a value.
I think it must be dev_3.5 but i'm not sure

**Comment by JanJaapKo** [comment]
Ì just pushed v1.4.9 where a line of debug logging will be printed per zwave device, also the ones that are not configured. So you can check on which one you get the expected values. Hope that helps.

**Comment by hemant5400z** [comment]
Just did some adtional testing and the sequence I need to use is:

3.1;3.3;3.5;3.6;3.4

![image](https://user-images.githubusercontent.com/16900394/213142216-556d28fe-a69b-4634-bc5d-4cb80a7da1d2.png)

I saw some activity on Toon-Opgewekt

My previous sequence was 3.1;3.3;3.5;3.4;3.6  which did not give me any data.

I will keep monitoring

Thanks,
Aniel

**Comment by MadPatrick** [comment]
@hemant5400z 
Is this working now for you ?

**Comment by hemant5400z** [comment]
> @hemant5400z Is this working now for you ?

Hi Yes, as far as I can see all is working/populated after I changed sequence to: 3.1;3.3;3.5;3.6;3.4

Hemant

**Comment by MadPatrick** [comment]
Good to hear
