### ISSUE TITLE
Error message : connect request from 'Toon' ignored.

### ISSUE THREAD

**Issue by MadPatrick** [MadPatrick/domoticz_toon#6]
Occasionally there is error message in Domoticz

2023-01-17 21:30:03.189 Error: Toon: CConnection_connect, connect request from 'Toon' ignored. Transport is connected.
2023-01-17 23:00:03.194 Error: Toon: CConnection_connect, connect request from 'Toon' ignored. Transport is connected.
2023-01-18 21:30:03.167 Error: Toon: CConnection_connect, connect request from 'Toon' ignored. Transport is connected.

When this appears the command is not executed

**Comment by JanJaapKo** [comment]
probably due to the Toon being saturated with connections?

**Comment by MadPatrick** [comment]
Must be indeed.
Is there something we can do about it or at least the given commando is executed again?
No i believe the commando is ignored due to this error

**Comment by MadPatrick** [comment]
It is a Dzvents script that is giving the error to the Toon.
Script was working for a few years with the Toon DzVents script.
Since the change from Dzvents Toon script to Plugin is giving this error
Strange because the device are the same

**Comment by MadPatrick** [comment]
Dzvents was not the the problem. 
It must the load of connections to the Toon. 
Can we reduce this or make delay between each connection so that they are not connection at the same time

**Comment by MadPatrick** [comment]
Mostly the error comes when a command is give to Domoticz and this gives the command to the Toon.
In a Dzvents script i have a command at 23:00 to go in sleepmode. The DzVentz give a command to Domoticz to set the Scene to "Sleep"

**Comment by MadPatrick** [comment]
Error come from to many connections in a short time.
Not sure if it is Domoticz related
